<template>
  <div class="loadingio-spinner-ellipsis-zxjtr6615h"
      v-show="loading"
      :can-cancel="true"
      :z-index="10">
    <div class="ldio-pjhnwjvb28e">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    isLoading: {
      type: Boolean, required: true
    }
  },
  data () {
    return {
      loading: true
    }
  },
  watch: {
    isLoading () {
      this.loading = this.isLoading
      console.log(this.loading)
    }
  }
}
</script>
<style>
@keyframes ldio-pjhnwjvb28e {
   0% { transform: translate(19.5px,70.5px) scale(0); }
  25% { transform: translate(19.5px,70.5px) scale(0); }
  50% { transform: translate(19.5px,70.5px) scale(1); }
  75% { transform: translate(70.5px,70.5px) scale(1); }
 100% { transform: translate(121.5px,70.5px) scale(1); }
}
@keyframes ldio-pjhnwjvb28e-r {
   0% { transform: translate(121.5px,70.5px) scale(1); }
 100% { transform: translate(121.5px,70.5px) scale(0); }
}
@keyframes ldio-pjhnwjvb28e-c {
   0% { background: #45664c }
  25% { background: #eae2cf }
  50% { background: #c6eccb }
  75% { background: #7d7767 }
 100% { background: #45664c }
}
.ldio-pjhnwjvb28e div {
  position: absolute;
  width: 9px;
  height: 9px;
  border-radius: 50%;
  transform: translate(70.5px,70.5px) scale(1);
  background: #45664c;
  animation: ldio-pjhnwjvb28e 1.5384615384615383s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-pjhnwjvb28e div:nth-child(1) {
  background: #7d7767;
  transform: translate(121.5px,70.5px) scale(1);
  animation: ldio-pjhnwjvb28e-r 0.3846153846153846s infinite cubic-bezier(0,0.5,0.5,1), ldio-pjhnwjvb28e-c 1.5384615384615383s infinite step-start;
}.ldio-pjhnwjvb28e div:nth-child(2) {
  animation-delay: -0.3846153846153846s;
  background: #45664c;
}.ldio-pjhnwjvb28e div:nth-child(3) {
  animation-delay: -0.7692307692307692s;
  background: #7d7767;
}.ldio-pjhnwjvb28e div:nth-child(4) {
  animation-delay: -1.1538461538461537s;
  background: #c6eccb;
}.ldio-pjhnwjvb28e div:nth-child(5) {
  animation-delay: -1.5384615384615383s;
  background: #eae2cf;
}
.loadingio-spinner-ellipsis-zxjtr6615h {
  overflow: hidden;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
  background-color: transparent;
}
.ldio-pjhnwjvb28e {
  width: auto;
  height: auto;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
/* generated by https://loading.io/ */
</style>
